config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'home/index'

  get 'dashboard/index'

  devise_for :users, controllers: { registrations: 'registrations' }
  resources :categories
  resources :items
end

app/views/layouts/_breadcrumb.html.erb
<%
  stack = [] unless local_assigns.has_key? :stack
%>
<section class="section is-title-bar">
  <div class="level">
    <div class="level-left">
      <div class="level-item">
        <ul>
          <% stack.each do |s| %>
            <li><%= s %></li>
          <% end %>
        </ul>
      </div>
    </div>
    <!--
    <div class="level-right">
      <div class="level-item">
        <div class="buttons is-right">
          <a href="https://github.com/vikdiesel/admin-one-bulma-dashboard" target="_blank" class="button is-primary">
            <span class="icon"><i class="mdi mdi-github-circle"></i></span>
            <span>GitHub</span>
          </a>
        </div>
      </div>
    </div>
    -->
  </div>
</section>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container-fluid">
    <div class="level">
      <div class="level-left">
        <div class="level-item">
          © 2023 Chatbot, Inc.
        </div>
      </div>
      <div class="level-right">
        <div class="level-item">
          <div class="logo">
            <a href="https://chatbot.ai">
              Chatbot.ai
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<nav id="navbar-main" class="navbar is-fixed-top">
  <div class="navbar-brand">
    <a class="navbar-item is-hidden-desktop jb-aside-mobile-toggle">
      <span class="icon"><i class="mdi mdi-forwardburger mdi-24px"></i></span>
    </a>
  </div>
  <div class="navbar-brand is-right">
    <a class="navbar-item is-hidden-desktop jb-navbar-menu-toggle" data-target="navbar-menu">
      <span class="icon"><i class="mdi mdi-dots-vertical"></i></span>
    </a>
  </div>
  <div class="navbar-menu fadeIn animated faster" id="navbar-menu">
    <div class="navbar-end">
      <div class="navbar-item has-dropdown has-dropdown-with-icons has-divider has-user-avatar is-hoverable">
        <a class="navbar-link is-arrowless">
          <div class="is-user-name">
            <span>
              <%= current_user.fullname %>
            </span>
          </div>
          <span class="icon"><i class="mdi mdi-chevron-down"></i></span>
        </a>
        <div class="navbar-dropdown">
          <%= link_to edit_user_registration_path, class: 'navbar-item' do %>
            <span class="icon"><i class="mdi mdi-account"></i></span>
            <span>Profile</span>
          <% end %>
          <!--
          <a class="navbar-item">
            <span class="icon"><i class="mdi mdi-settings"></i></span>
            <span>Settings</span>
          </a>
          <a class="navbar-item">
            <span class="icon"><i class="mdi mdi-email"></i></span>
            <span>Messages</span>
          </a>
          -->
          <hr class="navbar-divider">
          <%= link_to destroy_user_session_path, method: :delete, class: 'navbar-item', data: { turbo_method: :delete } do %>
            <span class="icon"><i class="mdi mdi-logout"></i></span>
            <span>Log Out</span>
          <% end %>
        </div>
      </div>
      <%= link_to destroy_user_session_path, class: 'navbar-item is-desktop-icon-only', data: { turbo_method: :delete } do %>
        <span class="icon"><i class="mdi mdi-logout"></i></span>
        <span>Log Out</span>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<aside class="aside is-placed-left is-expanded">
  <div class="aside-tools">
    <div class="aside-tools-label">
      <span><b>AvviCities</b> Admin</span>
    </div>
  </div>
  <div class="menu is-menu-main">
    <p class="menu-label">General</p>
    <ul class="menu-list">
      <li>
        <%= link_to dashboard_index_path, class: "has-icon #{'is-active' if controller_name == 'dashboard'}" do %>
          <span class="icon"><i class="mdi mdi-desktop-mac"></i></span>
          <span class="menu-item-label">Dashboard</span>
        <% end %>
      </li>
    </ul>
    <p class="menu-label">Data</p>
    <ul class="menu-list">
      <li>
        <%= link_to categories_path, class: "has-icon #{'is-active' if controller_name == 'categories'}" do %>
          <span class="icon"><i class="mdi mdi-table"></i></span>
          <span class="menu-item-label">Categories</span>
        <% end %>
      </li>
      <li>
        <%= link_to items_path, class: "has-icon #{'is-active' if controller_name == 'items'}" do %>
          <span class="icon"><i class="mdi mdi-table"></i></span>
          <span class="menu-item-label">Items</span>
        <% end %>
      </li>
    </ul>
  </div>
</aside>

app/views/layouts/_title.html.erb
<%
  title = '' unless local_assigns.has_key? :title
%>
<section class="hero is-hero-bar">
  <div class="hero-body">
    <div class="level">
      <div class="level-left">
        <div class="level-item">
          <h1 class="title">
          <%= title %>
          </h1>
        </div>
      </div>
      <div class="level-right" style="display: none;">
        <div class="level-item"></div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" class="<%= 'has-aside-left' if user_signed_in? %> has-aside-mobile-transition has-navbar-fixed-top has-aside-expanded">
  <head>
    <title>Avvi Backend</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.materialdesignicons.com/4.9.95/css/materialdesignicons.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div id="app">
      <% if user_signed_in? %>
        <%= render 'layouts/nav' %>
        <%= render 'layouts/sidebar' %>
      <% end %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>